/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stanley Creative (https://sketchfab.com/Stanley_Creative)
License: CC-BY-ND-4.0 (http://creativecommons.org/licenses/by-nd/4.0/)
Source: https://sketchfab.com/3d-models/saturn-v-nasa-7a2c9709ff8144c8b3b18ec84b5e112e
Title: Saturn V - NASA
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_94: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_104: THREE.Mesh;
    Object_106: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_114: THREE.Mesh;
    Object_116: THREE.Mesh;
    Object_118: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_124: THREE.Mesh;
    Object_126: THREE.Mesh;
    Object_128: THREE.Mesh;
    Object_130: THREE.Mesh;
    Object_132: THREE.Mesh;
    Object_134: THREE.Mesh;
    Object_136: THREE.Mesh;
    Object_138: THREE.Mesh;
    Object_140: THREE.Mesh;
    Object_142: THREE.Mesh;
    Object_144: THREE.Mesh;
    Object_146: THREE.Mesh;
    Object_148: THREE.Mesh;
    Object_150: THREE.Mesh;
    Object_152: THREE.Mesh;
    Object_154: THREE.Mesh;
    Object_156: THREE.Mesh;
    Object_158: THREE.Mesh;
    Object_160: THREE.Mesh;
    Object_162: THREE.Mesh;
    Object_164: THREE.Mesh;
    Object_166: THREE.Mesh;
    Object_168: THREE.Mesh;
    Object_170: THREE.Mesh;
    Object_172: THREE.Mesh;
    Object_174: THREE.Mesh;
    Object_176: THREE.Mesh;
    Object_178: THREE.Mesh;
    Object_180: THREE.Mesh;
    Object_182: THREE.Mesh;
    Object_184: THREE.Mesh;
    Object_186: THREE.Mesh;
    Object_188: THREE.Mesh;
    Object_190: THREE.Mesh;
    Object_192: THREE.Mesh;
    Object_194: THREE.Mesh;
    Object_196: THREE.Mesh;
    Object_198: THREE.Mesh;
    Object_200: THREE.Mesh;
    Object_202: THREE.Mesh;
    Object_204: THREE.Mesh;
    Object_206: THREE.Mesh;
    Object_208: THREE.Mesh;
    Object_210: THREE.Mesh;
    Object_212: THREE.Mesh;
    Object_214: THREE.Mesh;
    Object_216: THREE.Mesh;
    Object_219: THREE.Mesh;
    Object_222: THREE.Mesh;
    Object_224: THREE.Mesh;
    Object_226: THREE.Mesh;
    Object_228: THREE.Mesh;
    Object_230: THREE.Mesh;
    Object_232: THREE.Mesh;
    Object_234: THREE.Mesh;
    Object_236: THREE.Mesh;
    Object_238: THREE.Mesh;
    Object_240: THREE.Mesh;
    Object_242: THREE.Mesh;
    Object_244: THREE.Mesh;
    Object_246: THREE.Mesh;
    Object_248: THREE.Mesh;
    Object_250: THREE.Mesh;
    Object_252: THREE.Mesh;
    Object_255: THREE.Mesh;
    Object_258: THREE.Mesh;
  };
  materials: {
    Apollo_Metal: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Saturn_V_Main: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/rocket.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 0.9 * (1 / 0.018), 0]}
      >
        <group position={[0, 0, -99.185]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, -4.703, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Apollo_Metal}
            />
            <group position={[0, -0.003, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_13.geometry}
                material={materials.material_0}
                position={[0, -0.198, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_15.geometry}
                material={materials.material_0}
                position={[0, -0.43, 0]}
              />
            </group>
            <group position={[-1.955, 0.132, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_17.geometry}
                material={materials.material_0}
              />
              <group position={[-0.037, 0, 0]} rotation={[0, 0, 0.052]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.material_0}
                />
                <group position={[0, 1.515, 0]} rotation={[0, 0, -Math.PI / 2]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_0}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.material_0}
                    position={[-0.001, -0.038, 0]}
                  />
                </group>
              </group>
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.material_0}
              position={[0, 3.101, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.material_0}
              position={[0, 2.136, 0]}
              rotation={[0, Math.PI / 4, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Apollo_Metal}
          />
        </group>
        <group position={[0, 0, -102.406]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.Apollo_Metal}
            position={[0, -3.221, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.material_0}
            position={[0, 1.118, 0]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.material_0}
            position={[0, 1.118, 0]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.material_0}
            position={[0, 1.118, 0]}
            rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials.material_0}
            position={[0, 1.118, 0]}
            rotation={[0, -Math.PI / 4, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[0, 0.436, Math.PI / 4]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[Math.PI, 1.134, -2.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[Math.PI, -0.436, -2.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[0, -1.134, Math.PI / 4]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_50.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[0, -0.436, -Math.PI / 4]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_52.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[0, 1.134, -Math.PI / 4]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_54.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[Math.PI, 0.436, 2.356]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_56.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
            rotation={[-Math.PI, -1.134, 2.356]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_58.geometry}
            material={materials.material_0}
            position={[0, -0.595, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.material_0}
            position={[0, -0.595, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.material_0}
            position={[0, -0.595, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_64.geometry}
            material={materials.material_0}
            position={[0, -0.595, 0]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_66.geometry}
            material={materials.material_0}
            position={[0, -0.351, 0]}
            rotation={[0, 0, -1.169]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_68.geometry}
            material={materials.material_0}
            position={[0, -0.088, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_70.geometry}
            material={materials.material_0}
            position={[0, -0.088, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_72.geometry}
            material={materials.material_0}
            position={[0, -0.088, 0]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_74.geometry}
            material={materials.material_0}
            position={[0, -0.088, 0]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_76.geometry}
            material={materials.material_0}
            position={[0, -0.351, 0]}
            rotation={[-1.169, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_78.geometry}
            material={materials.material_0}
            position={[0, -0.351, 0]}
            rotation={[Math.PI, 0, 1.972]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_80.geometry}
            material={materials.material_0}
            position={[0, -0.351, 0]}
            rotation={[1.169, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_82.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[0, 0, -Math.PI / 4]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_84.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[-Math.PI / 4, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_86.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[Math.PI, 0, 2.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_88.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[Math.PI / 4, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_90.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[0, 0, -Math.PI / 4]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_92.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[-Math.PI / 4, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_94.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[Math.PI, 0, 2.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_96.geometry}
            material={materials.material_0}
            position={[0, -0.827, 0]}
            rotation={[Math.PI / 4, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_98.geometry}
            material={materials.Black}
            position={[0, 1.023, 0.604]}
            rotation={[-Math.PI / 6, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_100.geometry}
            material={materials.Black}
            position={[0.604, 1.023, 0]}
            rotation={[-Math.PI / 2, Math.PI / 3, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_102.geometry}
            material={materials.Black}
            position={[0, 1.023, -0.604]}
            rotation={[-2.618, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_104.geometry}
            material={materials.Black}
            position={[-0.604, 1.023, 0]}
            rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_106.geometry}
            material={materials.material_0}
            position={[0, 0.565, 0]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_110.geometry}
            material={materials.Saturn_V_Main}
          />
          <group position={[0, 4.28, 0]} scale={[1, 1, 0.962]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_120.geometry}
              material={materials.Apollo_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_122.geometry}
              material={materials.Apollo_Metal}
              position={[0, -2.313, 0]}
              rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_124.geometry}
              material={materials.Apollo_Metal}
              position={[-0.973, 1.852, 0.953]}
              rotation={[-Math.PI, 0.645, -Math.PI]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_126.geometry}
              material={materials.Apollo_Metal}
              position={[-0.973, 1.452, 0.953]}
              rotation={[-Math.PI, 0.645, -Math.PI]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_128.geometry}
              material={materials.Apollo_Metal}
              position={[-0.973, 1.052, 0.953]}
              rotation={[-Math.PI, 0.645, -Math.PI]}
              scale={[1.001, 1, 1.001]}
            />
          </group>
          <group position={[3.5, 4.28, 3.5]} scale={[1, 1, 0.962]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_130.geometry}
              material={materials.Apollo_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_132.geometry}
              material={materials.Apollo_Metal}
              position={[0, -2.313, 0]}
              rotation={[0, Math.PI / 4, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_134.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.852, -0.977]}
              rotation={[0, 0.785, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_136.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.452, -0.977]}
              rotation={[0, 0.785, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_138.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.052, -0.977]}
              rotation={[0, 0.785, 0]}
              scale={[1.001, 1, 1.001]}
            />
          </group>
          <group
            position={[3.5, 4.28, -3.5]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.962, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_140.geometry}
              material={materials.Apollo_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_142.geometry}
              material={materials.Apollo_Metal}
              position={[0, -2.313, 0]}
              rotation={[0, Math.PI / 4, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_144.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.852, -0.94]}
              rotation={[0, 0.746, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_146.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.452, -0.94]}
              rotation={[0, 0.746, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_148.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.052, -0.94]}
              rotation={[0, 0.746, 0]}
              scale={[1.001, 1, 1.001]}
            />
          </group>
          <group
            position={[-3.5, 4.28, -3.5]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1, 1, 0.962]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_150.geometry}
              material={materials.Apollo_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_152.geometry}
              material={materials.Apollo_Metal}
              position={[0, -2.313, 0]}
              rotation={[0, Math.PI / 4, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_154.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.852, -0.977]}
              rotation={[0, 0.786, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_156.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.452, -0.977]}
              rotation={[0, 0.786, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_158.geometry}
              material={materials.Apollo_Metal}
              position={[-0.952, 1.052, -0.977]}
              rotation={[0, 0.786, 0]}
              scale={[1.001, 1, 1.001]}
            />
          </group>
          <group
            position={[-3.5, 4.28, 3.5]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[0.962, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_160.geometry}
              material={materials.Apollo_Metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_162.geometry}
              material={materials.Apollo_Metal}
              position={[0, -2.313, 0]}
              rotation={[0, Math.PI / 4, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_164.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.852, -0.94]}
              rotation={[0, 0.747, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_166.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.452, -0.94]}
              rotation={[0, 0.747, 0]}
              scale={[1.001, 1, 1.001]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_168.geometry}
              material={materials.Apollo_Metal}
              position={[-0.989, 1.052, -0.94]}
              rotation={[0, 0.747, 0]}
              scale={[1.001, 1, 1.001]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_112.geometry}
            material={materials.Saturn_V_Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_114.geometry}
            material={materials.Saturn_V_Main}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_116.geometry}
            material={materials.Saturn_V_Main}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_118.geometry}
            material={materials.Saturn_V_Main}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_170.geometry}
            material={materials.material_0}
            position={[0, 6.536, 0]}
            scale={[1, 1, 0.962]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_172.geometry}
            material={materials.material_0}
            position={[0, 6.557, 0]}
            scale={[1, 1, 0.962]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_174.geometry}
            material={materials.Saturn_V_Main}
            scale={[1, 1, 0.962]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_176.geometry}
            material={materials.material_0}
            position={[0, 6.47, 0]}
            rotation={[0, 0.785, 0]}
            scale={[0.981, 1, 0.981]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_178.geometry}
            material={materials.material_0}
            position={[0, 6.47, 0]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[0.962, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_180.geometry}
            material={materials.Saturn_V_Main}
            position={[0, 9.426, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_182.geometry}
            material={materials.material_0}
            position={[-0.98, 6.404, -5.192]}
            rotation={[-Math.PI, 1.374, -Math.PI]}
          />
        </group>
        <group position={[0, 0, -42.1]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_184.geometry}
            material={materials.Saturn_V_Main}
          />
          <group position={[0, 2.922, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_216.geometry}
              material={materials.Saturn_V_Main}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_219.geometry}
              material={materials.material_0}
              rotation={[0, -Math.PI / 4, 0]}
            />
          </group>
          <group position={[0, 7.835, 0]} rotation={[0, 0.611, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_222.geometry}
              material={materials.material_0}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_224.geometry}
              material={materials.material_0}
              rotation={[-Math.PI, 0.107, -Math.PI]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_186.geometry}
            material={materials.material_0}
            position={[0.717, 4.587, 3.606]}
            rotation={[0, -1.374, -0.587]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_188.geometry}
            material={materials.material_0}
            position={[3.605, 4.587, 0.717]}
            rotation={[0, -0.196, -0.587]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_190.geometry}
            material={materials.material_0}
            position={[3.605, 4.587, -0.717]}
            rotation={[0, 0.196, -0.587]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_192.geometry}
            material={materials.material_0}
            position={[0.717, 4.587, -3.605]}
            rotation={[0, 1.374, -0.587]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_194.geometry}
            material={materials.material_0}
            position={[-0.718, 4.587, -3.605]}
            rotation={[Math.PI, 1.374, 2.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_196.geometry}
            material={materials.material_0}
            position={[-3.606, 4.587, -0.717]}
            rotation={[-Math.PI, 0.196, 2.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_198.geometry}
            material={materials.material_0}
            position={[-3.606, 4.587, 0.718]}
            rotation={[-Math.PI, -0.196, 2.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_200.geometry}
            material={materials.material_0}
            position={[-0.717, 4.587, 3.606]}
            rotation={[-Math.PI, -1.374, 2.555]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_202.geometry}
            material={materials.material_0}
            position={[0, 3.94, 0]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_204.geometry}
            material={materials.material_0}
            position={[0, 2.311, 0]}
            scale={[0.57, 0.532, 0.57]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_206.geometry}
            material={materials.material_0}
            position={[1.949, 2.311, -1.949]}
            rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
            scale={[0.57, 0.532, 0.57]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_208.geometry}
            material={materials.material_0}
            position={[-1.949, 2.311, 1.949]}
            rotation={[0, Math.PI / 4, 0]}
            scale={[0.57, 0.532, 0.57]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_210.geometry}
            material={materials.material_0}
            position={[-1.949, 2.311, -1.949]}
            rotation={[0, -Math.PI / 4, 0]}
            scale={[0.57, 0.532, 0.57]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_212.geometry}
            material={materials.material_0}
            position={[1.949, 2.311, 1.949]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            scale={[0.57, 0.532, 0.57]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_214.geometry}
            material={materials.material_0}
            position={[-2.038, 5.556, -4.874]}
            rotation={[-Math.PI, 1.165, -Math.PI]}
          />
        </group>
        <group position={[0, 0, -78.491]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_226.geometry}
            material={materials.Saturn_V_Main}
          />
          <group position={[0, 9.485, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_234.geometry}
              material={materials.Saturn_V_Main}
            />
            <group
              position={[2.271, 0, -2.271]}
              rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_236.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_238.geometry}
                material={materials.Saturn_V_Main}
                position={[0, 0, -3.212]}
                rotation={[0, -Math.PI / 4, 0]}
              />
            </group>
            <group position={[2.271, 0, 2.271]} rotation={[0, Math.PI / 4, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_240.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_242.geometry}
                material={materials.Saturn_V_Main}
                position={[0, 0, -3.212]}
                rotation={[0, -Math.PI / 4, 0]}
              />
            </group>
            <group
              position={[-2.271, 0, -2.271]}
              rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_244.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_246.geometry}
                material={materials.Saturn_V_Main}
                position={[0, 0, -3.212]}
                rotation={[0, -Math.PI / 4, 0]}
              />
            </group>
            <group
              position={[-2.271, 0, 2.271]}
              rotation={[0, -Math.PI / 4, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_248.geometry}
                material={materials.material_0}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_250.geometry}
                material={materials.Saturn_V_Main}
                position={[0, 0, -3.212]}
                rotation={[0, -Math.PI / 4, 0]}
              />
            </group>
          </group>
          <group position={[0, -11.591, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_252.geometry}
              material={materials.Saturn_V_Main}
            />
            <group position={[0, 4.098, 0]} rotation={[0, 0.611, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_255.geometry}
                material={materials.material_0}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
            <group position={[0, 1.536, 0]} rotation={[0, 0.611, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_258.geometry}
                material={materials.material_0}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_228.geometry}
            material={materials.material_0}
            position={[0, -2.727, -3.193]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_230.geometry}
            material={materials.material_0}
            position={[3.311, 1.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_232.geometry}
            material={materials.material_0}
            position={[0, -7.09, 0]}
            scale={[0.57, 0.532, 0.57]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_108.geometry}
          material={materials.material_0}
          position={[0, 0, -90.94]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/rocket.glb");
